version: "3.9"

services:
  cache:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 1264da6d8e728d9dd13c303ef88e224d
    volumes: 
     - cache:/data


volumes:
  cache:
    driver: local


